# Generated by Django 5.2.4 on 2025-07-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=500)),
                ('pdes', models.TextField(max_length=600)),
                ('prize', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
